//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalTestSystem {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LocalTestSystem.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to log off?.
        /// </summary>
        internal static string AskLogOff {
            get {
                return ResourceManager.GetString("AskLogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a password to Log In..
        /// </summary>
        internal static string AskPassword {
            get {
                return ResourceManager.GetString("AskPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Test Mode.
        /// </summary>
        internal static string CurrentTestMode {
            get {
                return ResourceManager.GetString("CurrentTestMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current user.
        /// </summary>
        internal static string CurrentUser {
            get {
                return ResourceManager.GetString("CurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle started with Serial Number: &apos;{0}&apos;.
        /// </summary>
        internal static string CycleStarted {
            get {
                return ResourceManager.GetString("CycleStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port is disabled in common mode parameters.
        /// </summary>
        internal static string Disabled_Prompt {
            get {
                return ResourceManager.GetString("Disabled_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distillation Complete.
        /// </summary>
        internal static string DistillComplete {
            get {
                return ResourceManager.GetString("DistillComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oil Distillation in Process.
        /// </summary>
        internal static string DistillPrompt {
            get {
                return ResourceManager.GetString("DistillPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filling Pump with Oil from Supply Tank.
        /// </summary>
        internal static string FillPrompt {
            get {
                return ResourceManager.GetString("FillPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle, Current Mode: {0}.
        /// </summary>
        internal static string Idle_Prompt {
            get {
                return ResourceManager.GetString("Idle_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan a valid model Number.  Matching scanned characters must be in ModelXRef table..
        /// </summary>
        internal static string InvalidModelNumber_Prompt {
            get {
                return ResourceManager.GetString("InvalidModelNumber_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password entered.  Please re-enter password..
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged Off.
        /// </summary>
        internal static string LoggedOff {
            get {
                return ResourceManager.GetString("LoggedOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold Drain Button to fill Supply Tank from makeup intake, Press Acknowledge when done.
        /// </summary>
        internal static string Makeup_Prompt {
            get {
                return ResourceManager.GetString("Makeup Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MCR Power Error, Check E STOP.
        /// </summary>
        internal static string MCRPowerError {
            get {
                return ResourceManager.GetString("MCRPowerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Number: {0}.
        /// </summary>
        internal static string ModelNumber {
            get {
                return ResourceManager.GetString("ModelNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (?&lt;=Model Number:\s)[^\r^\n]*.
        /// </summary>
        internal static string ModelNumberRegex {
            get {
                return ResourceManager.GetString("ModelNumberRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system must be in Autotest Mode to execute this command..
        /// </summary>
        internal static string MustBeInAutotest {
            get {
                return ResourceManager.GetString("MustBeInAutotest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must log off before a different user can log in..
        /// </summary>
        internal static string MustLogOff {
            get {
                return ResourceManager.GetString("MustLogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO TEST:  Test Aborted..
        /// </summary>
        internal static string NoTestTestAborted {
            get {
                return ResourceManager.GetString("NoTestTestAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System must be in AutoTest to execute this command..
        /// </summary>
        internal static string NotInAutoTestMode {
            get {
                return ResourceManager.GetString("NotInAutoTestMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator logged out..
        /// </summary>
        internal static string OpLoggedOff {
            get {
                return ResourceManager.GetString("OpLoggedOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Complete.
        /// </summary>
        internal static string ResetComplete {
            get {
                return ResourceManager.GetString("ResetComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Initiated.
        /// </summary>
        internal static string ResetInitiated {
            get {
                return ResourceManager.GetString("ResetInitiated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please scan &apos;LOGIN&apos; to begin..
        /// </summary>
        internal static string ScanLogin {
            get {
                return ResourceManager.GetString("ScanLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready for Sequence.
        /// </summary>
        internal static string SeqReadyForSequence {
            get {
                return ResourceManager.GetString("SeqReadyForSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for RESET after issue is resolved..
        /// </summary>
        internal static string SeqWaitForReset {
            get {
                return ResourceManager.GetString("SeqWaitForReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number: {0}.
        /// </summary>
        internal static string SerialNumberForLog {
            get {
                return ResourceManager.GetString("SerialNumberForLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oil Recovered.
        /// </summary>
        internal static string SlurpComplete {
            get {
                return ResourceManager.GetString("SlurpComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draining Oil from pump.
        /// </summary>
        internal static string SlurpPrompt {
            get {
                return ResourceManager.GetString("SlurpPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO TEST: Operator aborted the test..
        /// </summary>
        internal static string TestAborted {
            get {
                return ResourceManager.GetString("TestAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Aborted.
        /// </summary>
        internal static string TestAbortedTH {
            get {
                return ResourceManager.GetString("TestAbortedTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oil Transferred.
        /// </summary>
        internal static string TransferComplete {
            get {
                return ResourceManager.GetString("TransferComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferring Oil from Recovery Tank to Supply Tank.
        /// </summary>
        internal static string TransferPrompt {
            get {
                return ResourceManager.GetString("TransferPrompt", resourceCulture);
            }
        }
    }
}
