#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTIWindowsControlLibrary.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="VtiData")]
	public partial class VtiDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertGroupCommand(GroupCommand instance);
    partial void UpdateGroupCommand(GroupCommand instance);
    partial void DeleteGroupCommand(GroupCommand instance);
    partial void InsertGroup(Group instance);
    partial void UpdateGroup(Group instance);
    partial void DeleteGroup(Group instance);
    partial void InsertModelParameter(ModelParameter instance);
    partial void UpdateModelParameter(ModelParameter instance);
    partial void DeleteModelParameter(ModelParameter instance);
    partial void InsertModel(Model instance);
    partial void UpdateModel(Model instance);
    partial void DeleteModel(Model instance);
    partial void InsertSchemaChange(SchemaChange instance);
    partial void UpdateSchemaChange(SchemaChange instance);
    partial void DeleteSchemaChange(SchemaChange instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void InsertUutDefect(UutDefect instance);
    partial void UpdateUutDefect(UutDefect instance);
    partial void DeleteUutDefect(UutDefect instance);
    partial void InsertUutRecordDetail(UutRecordDetail instance);
    partial void UpdateUutRecordDetail(UutRecordDetail instance);
    partial void DeleteUutRecordDetail(UutRecordDetail instance);
    partial void InsertUutRecord(UutRecord instance);
    partial void UpdateUutRecord(UutRecord instance);
    partial void DeleteUutRecord(UutRecord instance);
    partial void InsertModelXRef(ModelXRef instance);
    partial void UpdateModelXRef(ModelXRef instance);
    partial void DeleteModelXRef(ModelXRef instance);
    #endregion
		
		public VtiDataContext() : 
				base(global::VTIWindowsControlLibrary.Properties.Settings.Default.VtiDataConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public VtiDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VtiDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VtiDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VtiDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<GroupCommand> GroupCommands
		{
			get
			{
				return this.GetTable<GroupCommand>();
			}
		}
		
		public System.Data.Linq.Table<Group> Groups
		{
			get
			{
				return this.GetTable<Group>();
			}
		}
		
		public System.Data.Linq.Table<ModelParameter> ModelParameters
		{
			get
			{
				return this.GetTable<ModelParameter>();
			}
		}
		
		public System.Data.Linq.Table<Model> Models
		{
			get
			{
				return this.GetTable<Model>();
			}
		}
		
		public System.Data.Linq.Table<SchemaChange> SchemaChanges
		{
			get
			{
				return this.GetTable<SchemaChange>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<UutDefect> UutDefects
		{
			get
			{
				return this.GetTable<UutDefect>();
			}
		}
		
		public System.Data.Linq.Table<UutRecordDetail> UutRecordDetails
		{
			get
			{
				return this.GetTable<UutRecordDetail>();
			}
		}
		
		public System.Data.Linq.Table<UutRecord> UutRecords
		{
			get
			{
				return this.GetTable<UutRecord>();
			}
		}
		
		public System.Data.Linq.Table<ModelXRef> ModelXRefs
		{
			get
			{
				return this.GetTable<ModelXRef>();
			}
		}
	}
	
	[Table(Name="dbo.GroupCommands")]
	public partial class GroupCommand : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private string _GroupID;
		
		private string _CommandID;
		
		private EntityRef<Group> _Group;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnGroupIDChanging(string value);
    partial void OnGroupIDChanged();
    partial void OnCommandIDChanging(string value);
    partial void OnCommandIDChanged();
    #endregion
		
		public GroupCommand()
		{
			this._Group = default(EntityRef<Group>);
			OnCreated();
		}
		
		[Column(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[Column(Storage="_GroupID", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string GroupID
		{
			get
			{
				return this._GroupID;
			}
			set
			{
				if ((this._GroupID != value))
				{
					if (this._Group.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnGroupIDChanging(value);
					this.SendPropertyChanging();
					this._GroupID = value;
					this.SendPropertyChanged("GroupID");
					this.OnGroupIDChanged();
				}
			}
		}
		
		[Column(Storage="_CommandID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CommandID
		{
			get
			{
				return this._CommandID;
			}
			set
			{
				if ((this._CommandID != value))
				{
					this.OnCommandIDChanging(value);
					this.SendPropertyChanging();
					this._CommandID = value;
					this.SendPropertyChanged("CommandID");
					this.OnCommandIDChanged();
				}
			}
		}
		
		[Association(Name="Group_GroupCommand", Storage="_Group", ThisKey="GroupID", OtherKey="GroupID", IsForeignKey=true)]
		public Group Group
		{
			get
			{
				return this._Group.Entity;
			}
			set
			{
				Group previousValue = this._Group.Entity;
				if (((previousValue != value) 
							|| (this._Group.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Group.Entity = null;
						previousValue.GroupCommands.Remove(this);
					}
					this._Group.Entity = value;
					if ((value != null))
					{
						value.GroupCommands.Add(this);
						this._GroupID = value.GroupID;
					}
					else
					{
						this._GroupID = default(string);
					}
					this.SendPropertyChanged("Group");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.Groups")]
	public partial class Group : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _GroupID;
		
		private bool _IsLocked;
		
		private EntitySet<GroupCommand> _GroupCommands;
		
		private EntitySet<User> _Users;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGroupIDChanging(string value);
    partial void OnGroupIDChanged();
    partial void OnIsLockedChanging(bool value);
    partial void OnIsLockedChanged();
    #endregion
		
		public Group()
		{
			this._GroupCommands = new EntitySet<GroupCommand>(new Action<GroupCommand>(this.attach_GroupCommands), new Action<GroupCommand>(this.detach_GroupCommands));
			this._Users = new EntitySet<User>(new Action<User>(this.attach_Users), new Action<User>(this.detach_Users));
			OnCreated();
		}
		
		[Column(Storage="_GroupID", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string GroupID
		{
			get
			{
				return this._GroupID;
			}
			set
			{
				if ((this._GroupID != value))
				{
					this.OnGroupIDChanging(value);
					this.SendPropertyChanging();
					this._GroupID = value;
					this.SendPropertyChanged("GroupID");
					this.OnGroupIDChanged();
				}
			}
		}
		
		[Column(Storage="_IsLocked", DbType="Bit NOT NULL")]
		public bool IsLocked
		{
			get
			{
				return this._IsLocked;
			}
			set
			{
				if ((this._IsLocked != value))
				{
					this.OnIsLockedChanging(value);
					this.SendPropertyChanging();
					this._IsLocked = value;
					this.SendPropertyChanged("IsLocked");
					this.OnIsLockedChanged();
				}
			}
		}
		
		[Association(Name="Group_GroupCommand", Storage="_GroupCommands", ThisKey="GroupID", OtherKey="GroupID")]
		public EntitySet<GroupCommand> GroupCommands
		{
			get
			{
				return this._GroupCommands;
			}
			set
			{
				this._GroupCommands.Assign(value);
			}
		}
		
		[Association(Name="Group_User", Storage="_Users", ThisKey="GroupID", OtherKey="GroupID")]
		public EntitySet<User> Users
		{
			get
			{
				return this._Users;
			}
			set
			{
				this._Users.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GroupCommands(GroupCommand entity)
		{
			this.SendPropertyChanging();
			entity.Group = this;
		}
		
		private void detach_GroupCommands(GroupCommand entity)
		{
			this.SendPropertyChanging();
			entity.Group = null;
		}
		
		private void attach_Users(User entity)
		{
			this.SendPropertyChanging();
			entity.Group = this;
		}
		
		private void detach_Users(User entity)
		{
			this.SendPropertyChanging();
			entity.Group = null;
		}
	}
	
	[Table(Name="dbo.ModelParameters")]
	public partial class ModelParameter : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private string _ModelNo;
		
		private string _ParameterID;
		
		private string _ProcessValue;
		
		private string _LastModifiedBy;
		
		private System.Nullable<System.DateTime> _LastModified;
		
		private EntityRef<Model> _Model;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnModelNoChanging(string value);
    partial void OnModelNoChanged();
    partial void OnParameterIDChanging(string value);
    partial void OnParameterIDChanged();
    partial void OnProcessValueChanging(string value);
    partial void OnProcessValueChanged();
    partial void OnLastModifiedByChanging(string value);
    partial void OnLastModifiedByChanged();
    partial void OnLastModifiedChanging(System.Nullable<System.DateTime> value);
    partial void OnLastModifiedChanged();
    #endregion
		
		public ModelParameter()
		{
			this._Model = default(EntityRef<Model>);
			OnCreated();
		}
		
		[Column(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[Column(Storage="_ModelNo", DbType="NVarChar(50)")]
		public string ModelNo
		{
			get
			{
				return this._ModelNo;
			}
			set
			{
				if ((this._ModelNo != value))
				{
					if (this._Model.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnModelNoChanging(value);
					this.SendPropertyChanging();
					this._ModelNo = value;
					this.SendPropertyChanged("ModelNo");
					this.OnModelNoChanged();
				}
			}
		}
		
		[Column(Storage="_ParameterID", DbType="NVarChar(50)")]
		public string ParameterID
		{
			get
			{
				return this._ParameterID;
			}
			set
			{
				if ((this._ParameterID != value))
				{
					this.OnParameterIDChanging(value);
					this.SendPropertyChanging();
					this._ParameterID = value;
					this.SendPropertyChanged("ParameterID");
					this.OnParameterIDChanged();
				}
			}
		}
		
		[Column(Storage="_ProcessValue", DbType="NVarChar(255)")]
		public string ProcessValue
		{
			get
			{
				return this._ProcessValue;
			}
			set
			{
				if ((this._ProcessValue != value))
				{
					this.OnProcessValueChanging(value);
					this.SendPropertyChanging();
					this._ProcessValue = value;
					this.SendPropertyChanged("ProcessValue");
					this.OnProcessValueChanged();
				}
			}
		}
		
		[Column(Storage="_LastModifiedBy", DbType="NVarChar(50)")]
		public string LastModifiedBy
		{
			get
			{
				return this._LastModifiedBy;
			}
			set
			{
				if ((this._LastModifiedBy != value))
				{
					this.OnLastModifiedByChanging(value);
					this.SendPropertyChanging();
					this._LastModifiedBy = value;
					this.SendPropertyChanged("LastModifiedBy");
					this.OnLastModifiedByChanged();
				}
			}
		}
		
		[Column(Storage="_LastModified", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastModified
		{
			get
			{
				return this._LastModified;
			}
			set
			{
				if ((this._LastModified != value))
				{
					this.OnLastModifiedChanging(value);
					this.SendPropertyChanging();
					this._LastModified = value;
					this.SendPropertyChanged("LastModified");
					this.OnLastModifiedChanged();
				}
			}
		}
		
		[Association(Name="Model_ModelParameter", Storage="_Model", ThisKey="ModelNo", OtherKey="ModelNo", IsForeignKey=true)]
		public Model Model
		{
			get
			{
				return this._Model.Entity;
			}
			set
			{
				Model previousValue = this._Model.Entity;
				if (((previousValue != value) 
							|| (this._Model.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Model.Entity = null;
						previousValue.ModelParameters.Remove(this);
					}
					this._Model.Entity = value;
					if ((value != null))
					{
						value.ModelParameters.Add(this);
						this._ModelNo = value.ModelNo;
					}
					else
					{
						this._ModelNo = default(string);
					}
					this.SendPropertyChanged("Model");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.Models")]
	public partial class Model : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ModelNo;
		
		private string _LastModifiedBy;
		
		private System.Nullable<System.DateTime> _LastModified;
		
		private EntitySet<ModelParameter> _ModelParameters;
		
		private EntitySet<UutRecord> _UutRecords;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnModelNoChanging(string value);
    partial void OnModelNoChanged();
    partial void OnLastModifiedByChanging(string value);
    partial void OnLastModifiedByChanged();
    partial void OnLastModifiedChanging(System.Nullable<System.DateTime> value);
    partial void OnLastModifiedChanged();
    #endregion
		
		public Model()
		{
			this._ModelParameters = new EntitySet<ModelParameter>(new Action<ModelParameter>(this.attach_ModelParameters), new Action<ModelParameter>(this.detach_ModelParameters));
			this._UutRecords = new EntitySet<UutRecord>(new Action<UutRecord>(this.attach_UutRecords), new Action<UutRecord>(this.detach_UutRecords));
			OnCreated();
		}
		
		[Column(Storage="_ModelNo", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ModelNo
		{
			get
			{
				return this._ModelNo;
			}
			set
			{
				if ((this._ModelNo != value))
				{
					this.OnModelNoChanging(value);
					this.SendPropertyChanging();
					this._ModelNo = value;
					this.SendPropertyChanged("ModelNo");
					this.OnModelNoChanged();
				}
			}
		}
		
		[Column(Storage="_LastModifiedBy", DbType="NVarChar(50)")]
		public string LastModifiedBy
		{
			get
			{
				return this._LastModifiedBy;
			}
			set
			{
				if ((this._LastModifiedBy != value))
				{
					this.OnLastModifiedByChanging(value);
					this.SendPropertyChanging();
					this._LastModifiedBy = value;
					this.SendPropertyChanged("LastModifiedBy");
					this.OnLastModifiedByChanged();
				}
			}
		}
		
		[Column(Storage="_LastModified", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastModified
		{
			get
			{
				return this._LastModified;
			}
			set
			{
				if ((this._LastModified != value))
				{
					this.OnLastModifiedChanging(value);
					this.SendPropertyChanging();
					this._LastModified = value;
					this.SendPropertyChanged("LastModified");
					this.OnLastModifiedChanged();
				}
			}
		}
		
		[Association(Name="Model_ModelParameter", Storage="_ModelParameters", ThisKey="ModelNo", OtherKey="ModelNo")]
		public EntitySet<ModelParameter> ModelParameters
		{
			get
			{
				return this._ModelParameters;
			}
			set
			{
				this._ModelParameters.Assign(value);
			}
		}
		
		[Association(Name="Model_UutRecord", Storage="_UutRecords", ThisKey="ModelNo", OtherKey="ModelNo")]
		public EntitySet<UutRecord> UutRecords
		{
			get
			{
				return this._UutRecords;
			}
			set
			{
				this._UutRecords.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ModelParameters(ModelParameter entity)
		{
			this.SendPropertyChanging();
			entity.Model = this;
		}
		
		private void detach_ModelParameters(ModelParameter entity)
		{
			this.SendPropertyChanging();
			entity.Model = null;
		}
		
		private void attach_UutRecords(UutRecord entity)
		{
			this.SendPropertyChanging();
			entity.Model = this;
		}
		
		private void detach_UutRecords(UutRecord entity)
		{
			this.SendPropertyChanging();
			entity.Model = null;
		}
	}
	
	[Table(Name="dbo.SchemaChanges")]
	public partial class SchemaChange : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _Major;
		
		private System.Nullable<int> _Minor;
		
		private System.Nullable<int> _Release;
		
		private string _Script_name;
		
		private System.Nullable<System.DateTime> _Applied;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMajorChanging(System.Nullable<int> value);
    partial void OnMajorChanged();
    partial void OnMinorChanging(System.Nullable<int> value);
    partial void OnMinorChanged();
    partial void OnReleaseChanging(System.Nullable<int> value);
    partial void OnReleaseChanged();
    partial void OnScript_nameChanging(string value);
    partial void OnScript_nameChanged();
    partial void OnAppliedChanging(System.Nullable<System.DateTime> value);
    partial void OnAppliedChanged();
    #endregion
		
		public SchemaChange()
		{
			OnCreated();
		}
		
		[Column(Name="id", Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[Column(Name="major", Storage="_Major", DbType="Int")]
		public System.Nullable<int> Major
		{
			get
			{
				return this._Major;
			}
			set
			{
				if ((this._Major != value))
				{
					this.OnMajorChanging(value);
					this.SendPropertyChanging();
					this._Major = value;
					this.SendPropertyChanged("Major");
					this.OnMajorChanged();
				}
			}
		}
		
		[Column(Name="minor", Storage="_Minor", DbType="Int")]
		public System.Nullable<int> Minor
		{
			get
			{
				return this._Minor;
			}
			set
			{
				if ((this._Minor != value))
				{
					this.OnMinorChanging(value);
					this.SendPropertyChanging();
					this._Minor = value;
					this.SendPropertyChanged("Minor");
					this.OnMinorChanged();
				}
			}
		}
		
		[Column(Name="release", Storage="_Release", DbType="Int")]
		public System.Nullable<int> Release
		{
			get
			{
				return this._Release;
			}
			set
			{
				if ((this._Release != value))
				{
					this.OnReleaseChanging(value);
					this.SendPropertyChanging();
					this._Release = value;
					this.SendPropertyChanged("Release");
					this.OnReleaseChanged();
				}
			}
		}
		
		[Column(Name="script_name", Storage="_Script_name", DbType="VarChar(255)")]
		public string Script_name
		{
			get
			{
				return this._Script_name;
			}
			set
			{
				if ((this._Script_name != value))
				{
					this.OnScript_nameChanging(value);
					this.SendPropertyChanging();
					this._Script_name = value;
					this.SendPropertyChanged("Script_name");
					this.OnScript_nameChanged();
				}
			}
		}
		
		[Column(Name="applied", Storage="_Applied", DbType="DateTime")]
		public System.Nullable<System.DateTime> Applied
		{
			get
			{
				return this._Applied;
			}
			set
			{
				if ((this._Applied != value))
				{
					this.OnAppliedChanging(value);
					this.SendPropertyChanging();
					this._Applied = value;
					this.SendPropertyChanged("Applied");
					this.OnAppliedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.Users")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _OpID;
		
		private string _Password;
		
		private string _GroupID;
		
		private bool _IsLocked;
		
		private EntityRef<Group> _Group;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnOpIDChanging(string value);
    partial void OnOpIDChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnGroupIDChanging(string value);
    partial void OnGroupIDChanged();
    partial void OnIsLockedChanging(bool value);
    partial void OnIsLockedChanged();
    #endregion
		
		public User()
		{
			this._Group = default(EntityRef<Group>);
			OnCreated();
		}
		
		[Column(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[Column(Storage="_OpID", DbType="NVarChar(16) NOT NULL", CanBeNull=false)]
		public string OpID
		{
			get
			{
				return this._OpID;
			}
			set
			{
				if ((this._OpID != value))
				{
					this.OnOpIDChanging(value);
					this.SendPropertyChanging();
					this._OpID = value;
					this.SendPropertyChanged("OpID");
					this.OnOpIDChanged();
				}
			}
		}
		
		[Column(Storage="_Password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[Column(Storage="_GroupID", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string GroupID
		{
			get
			{
				return this._GroupID;
			}
			set
			{
				if ((this._GroupID != value))
				{
					if (this._Group.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnGroupIDChanging(value);
					this.SendPropertyChanging();
					this._GroupID = value;
					this.SendPropertyChanged("GroupID");
					this.OnGroupIDChanged();
				}
			}
		}
		
		[Column(Storage="_IsLocked", DbType="Bit NOT NULL")]
		public bool IsLocked
		{
			get
			{
				return this._IsLocked;
			}
			set
			{
				if ((this._IsLocked != value))
				{
					this.OnIsLockedChanging(value);
					this.SendPropertyChanging();
					this._IsLocked = value;
					this.SendPropertyChanged("IsLocked");
					this.OnIsLockedChanged();
				}
			}
		}
		
		[Association(Name="Group_User", Storage="_Group", ThisKey="GroupID", OtherKey="GroupID", IsForeignKey=true)]
		public Group Group
		{
			get
			{
				return this._Group.Entity;
			}
			set
			{
				Group previousValue = this._Group.Entity;
				if (((previousValue != value) 
							|| (this._Group.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Group.Entity = null;
						previousValue.Users.Remove(this);
					}
					this._Group.Entity = value;
					if ((value != null))
					{
						value.Users.Add(this);
						this._GroupID = value.GroupID;
					}
					else
					{
						this._GroupID = default(string);
					}
					this.SendPropertyChanged("Group");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.UutDefects")]
	public partial class UutDefect : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private long _UutRecordID;
		
		private string _Defect;
		
		private string _Category;
		
		private string _Description;
		
		private EntityRef<UutRecord> _UutRecord;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnUutRecordIDChanging(long value);
    partial void OnUutRecordIDChanged();
    partial void OnDefectChanging(string value);
    partial void OnDefectChanged();
    partial void OnCategoryChanging(string value);
    partial void OnCategoryChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    #endregion
		
		public UutDefect()
		{
			this._UutRecord = default(EntityRef<UutRecord>);
			OnCreated();
		}
		
		[Column(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[Column(Storage="_UutRecordID", DbType="BigInt NOT NULL")]
		public long UutRecordID
		{
			get
			{
				return this._UutRecordID;
			}
			set
			{
				if ((this._UutRecordID != value))
				{
					if (this._UutRecord.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUutRecordIDChanging(value);
					this.SendPropertyChanging();
					this._UutRecordID = value;
					this.SendPropertyChanged("UutRecordID");
					this.OnUutRecordIDChanged();
				}
			}
		}
		
		[Column(Storage="_Defect", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string Defect
		{
			get
			{
				return this._Defect;
			}
			set
			{
				if ((this._Defect != value))
				{
					this.OnDefectChanging(value);
					this.SendPropertyChanging();
					this._Defect = value;
					this.SendPropertyChanged("Defect");
					this.OnDefectChanged();
				}
			}
		}
		
		[Column(Storage="_Category", DbType="NVarChar(25)")]
		public string Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this.OnCategoryChanging(value);
					this.SendPropertyChanging();
					this._Category = value;
					this.SendPropertyChanged("Category");
					this.OnCategoryChanged();
				}
			}
		}
		
		[Column(Storage="_Description", DbType="NVarChar(50)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[Association(Name="UutRecord_UutDefect", Storage="_UutRecord", ThisKey="UutRecordID", OtherKey="ID", IsForeignKey=true, DeleteOnNull=true)]
		public UutRecord UutRecord
		{
			get
			{
				return this._UutRecord.Entity;
			}
			set
			{
				UutRecord previousValue = this._UutRecord.Entity;
				if (((previousValue != value) 
							|| (this._UutRecord.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._UutRecord.Entity = null;
						previousValue.UutDefects.Remove(this);
					}
					this._UutRecord.Entity = value;
					if ((value != null))
					{
						value.UutDefects.Add(this);
						this._UutRecordID = value.ID;
					}
					else
					{
						this._UutRecordID = default(long);
					}
					this.SendPropertyChanged("UutRecord");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.UutRecordDetails")]
	public partial class UutRecordDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private long _UutRecordID;
		
		private System.DateTime _DateTime;
		
		private string _Test;
		
		private string _Result;
		
		private string _ValueName;
		
		private System.Nullable<double> _Value;
		
		private string _MinSetpointName;
		
		private System.Nullable<double> _MinSetpoint;
		
		private string _MaxSetpointName;
		
		private System.Nullable<double> _MaxSetpoint;
		
		private string _Units;
		
		private System.Nullable<double> _ElapsedTime;
		
		private EntityRef<UutRecord> _UutRecord;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnUutRecordIDChanging(long value);
    partial void OnUutRecordIDChanged();
    partial void OnDateTimeChanging(System.DateTime value);
    partial void OnDateTimeChanged();
    partial void OnTestChanging(string value);
    partial void OnTestChanged();
    partial void OnResultChanging(string value);
    partial void OnResultChanged();
    partial void OnValueNameChanging(string value);
    partial void OnValueNameChanged();
    partial void OnValueChanging(System.Nullable<double> value);
    partial void OnValueChanged();
    partial void OnMinSetpointNameChanging(string value);
    partial void OnMinSetpointNameChanged();
    partial void OnMinSetpointChanging(System.Nullable<double> value);
    partial void OnMinSetpointChanged();
    partial void OnMaxSetpointNameChanging(string value);
    partial void OnMaxSetpointNameChanged();
    partial void OnMaxSetpointChanging(System.Nullable<double> value);
    partial void OnMaxSetpointChanged();
    partial void OnUnitsChanging(string value);
    partial void OnUnitsChanged();
    partial void OnElapsedTimeChanging(System.Nullable<double> value);
    partial void OnElapsedTimeChanged();
    #endregion
		
		public UutRecordDetail()
		{
			this._UutRecord = default(EntityRef<UutRecord>);
			OnCreated();
		}
		
		[Column(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[Column(Storage="_UutRecordID", DbType="BigInt NOT NULL")]
		public long UutRecordID
		{
			get
			{
				return this._UutRecordID;
			}
			set
			{
				if ((this._UutRecordID != value))
				{
					if (this._UutRecord.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUutRecordIDChanging(value);
					this.SendPropertyChanging();
					this._UutRecordID = value;
					this.SendPropertyChanged("UutRecordID");
					this.OnUutRecordIDChanged();
				}
			}
		}
		
		[Column(Storage="_DateTime", DbType="DateTime NOT NULL")]
		public System.DateTime DateTime
		{
			get
			{
				return this._DateTime;
			}
			set
			{
				if ((this._DateTime != value))
				{
					this.OnDateTimeChanging(value);
					this.SendPropertyChanging();
					this._DateTime = value;
					this.SendPropertyChanged("DateTime");
					this.OnDateTimeChanged();
				}
			}
		}
		
		[Column(Storage="_Test", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Test
		{
			get
			{
				return this._Test;
			}
			set
			{
				if ((this._Test != value))
				{
					this.OnTestChanging(value);
					this.SendPropertyChanging();
					this._Test = value;
					this.SendPropertyChanged("Test");
					this.OnTestChanged();
				}
			}
		}
		
		[Column(Storage="_Result", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Result
		{
			get
			{
				return this._Result;
			}
			set
			{
				if ((this._Result != value))
				{
					this.OnResultChanging(value);
					this.SendPropertyChanging();
					this._Result = value;
					this.SendPropertyChanged("Result");
					this.OnResultChanged();
				}
			}
		}
		
		[Column(Storage="_ValueName", DbType="NVarChar(50)")]
		public string ValueName
		{
			get
			{
				return this._ValueName;
			}
			set
			{
				if ((this._ValueName != value))
				{
					this.OnValueNameChanging(value);
					this.SendPropertyChanging();
					this._ValueName = value;
					this.SendPropertyChanged("ValueName");
					this.OnValueNameChanged();
				}
			}
		}
		
		[Column(Storage="_Value", DbType="Float")]
		public System.Nullable<double> Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				if ((this._Value != value))
				{
					this.OnValueChanging(value);
					this.SendPropertyChanging();
					this._Value = value;
					this.SendPropertyChanged("Value");
					this.OnValueChanged();
				}
			}
		}
		
		[Column(Storage="_MinSetpointName", DbType="NVarChar(50)")]
		public string MinSetpointName
		{
			get
			{
				return this._MinSetpointName;
			}
			set
			{
				if ((this._MinSetpointName != value))
				{
					this.OnMinSetpointNameChanging(value);
					this.SendPropertyChanging();
					this._MinSetpointName = value;
					this.SendPropertyChanged("MinSetpointName");
					this.OnMinSetpointNameChanged();
				}
			}
		}
		
		[Column(Storage="_MinSetpoint", DbType="Float")]
		public System.Nullable<double> MinSetpoint
		{
			get
			{
				return this._MinSetpoint;
			}
			set
			{
				if ((this._MinSetpoint != value))
				{
					this.OnMinSetpointChanging(value);
					this.SendPropertyChanging();
					this._MinSetpoint = value;
					this.SendPropertyChanged("MinSetpoint");
					this.OnMinSetpointChanged();
				}
			}
		}
		
		[Column(Storage="_MaxSetpointName", DbType="NVarChar(50)")]
		public string MaxSetpointName
		{
			get
			{
				return this._MaxSetpointName;
			}
			set
			{
				if ((this._MaxSetpointName != value))
				{
					this.OnMaxSetpointNameChanging(value);
					this.SendPropertyChanging();
					this._MaxSetpointName = value;
					this.SendPropertyChanged("MaxSetpointName");
					this.OnMaxSetpointNameChanged();
				}
			}
		}
		
		[Column(Storage="_MaxSetpoint", DbType="Float")]
		public System.Nullable<double> MaxSetpoint
		{
			get
			{
				return this._MaxSetpoint;
			}
			set
			{
				if ((this._MaxSetpoint != value))
				{
					this.OnMaxSetpointChanging(value);
					this.SendPropertyChanging();
					this._MaxSetpoint = value;
					this.SendPropertyChanged("MaxSetpoint");
					this.OnMaxSetpointChanged();
				}
			}
		}
		
		[Column(Storage="_Units", DbType="NVarChar(50)")]
		public string Units
		{
			get
			{
				return this._Units;
			}
			set
			{
				if ((this._Units != value))
				{
					this.OnUnitsChanging(value);
					this.SendPropertyChanging();
					this._Units = value;
					this.SendPropertyChanged("Units");
					this.OnUnitsChanged();
				}
			}
		}
		
		[Column(Storage="_ElapsedTime", DbType="Float")]
		public System.Nullable<double> ElapsedTime
		{
			get
			{
				return this._ElapsedTime;
			}
			set
			{
				if ((this._ElapsedTime != value))
				{
					this.OnElapsedTimeChanging(value);
					this.SendPropertyChanging();
					this._ElapsedTime = value;
					this.SendPropertyChanged("ElapsedTime");
					this.OnElapsedTimeChanged();
				}
			}
		}
		
		[Association(Name="UutRecord_UutRecordDetail", Storage="_UutRecord", ThisKey="UutRecordID", OtherKey="ID", IsForeignKey=true, DeleteOnNull=true)]
		public UutRecord UutRecord
		{
			get
			{
				return this._UutRecord.Entity;
			}
			set
			{
				UutRecord previousValue = this._UutRecord.Entity;
				if (((previousValue != value) 
							|| (this._UutRecord.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._UutRecord.Entity = null;
						previousValue.UutRecordDetails.Remove(this);
					}
					this._UutRecord.Entity = value;
					if ((value != null))
					{
						value.UutRecordDetails.Add(this);
						this._UutRecordID = value.ID;
					}
					else
					{
						this._UutRecordID = default(long);
					}
					this.SendPropertyChanged("UutRecord");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.UutRecords")]
	public partial class UutRecord : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private string _SerialNo;
		
		private string _ModelNo;
		
		private System.DateTime _DateTime;
		
		private string _SystemID;
		
		private string _OpID;
		
		private string _TestType;
		
		private string _TestResult;
		
		private string _TestPort;
		
		private EntitySet<UutDefect> _UutDefects;
		
		private EntitySet<UutRecordDetail> _UutRecordDetails;
		
		private EntityRef<Model> _Model;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnSerialNoChanging(string value);
    partial void OnSerialNoChanged();
    partial void OnModelNoChanging(string value);
    partial void OnModelNoChanged();
    partial void OnDateTimeChanging(System.DateTime value);
    partial void OnDateTimeChanged();
    partial void OnSystemIDChanging(string value);
    partial void OnSystemIDChanged();
    partial void OnOpIDChanging(string value);
    partial void OnOpIDChanged();
    partial void OnTestTypeChanging(string value);
    partial void OnTestTypeChanged();
    partial void OnTestResultChanging(string value);
    partial void OnTestResultChanged();
    partial void OnTestPortChanging(string value);
    partial void OnTestPortChanged();
    #endregion
		
		public UutRecord()
		{
			this._UutDefects = new EntitySet<UutDefect>(new Action<UutDefect>(this.attach_UutDefects), new Action<UutDefect>(this.detach_UutDefects));
			this._UutRecordDetails = new EntitySet<UutRecordDetail>(new Action<UutRecordDetail>(this.attach_UutRecordDetails), new Action<UutRecordDetail>(this.detach_UutRecordDetails));
			this._Model = default(EntityRef<Model>);
			OnCreated();
		}
		
		[Column(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[Column(Storage="_SerialNo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SerialNo
		{
			get
			{
				return this._SerialNo;
			}
			set
			{
				if ((this._SerialNo != value))
				{
					this.OnSerialNoChanging(value);
					this.SendPropertyChanging();
					this._SerialNo = value;
					this.SendPropertyChanged("SerialNo");
					this.OnSerialNoChanged();
				}
			}
		}
		
		[Column(Storage="_ModelNo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ModelNo
		{
			get
			{
				return this._ModelNo;
			}
			set
			{
				if ((this._ModelNo != value))
				{
					if (this._Model.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnModelNoChanging(value);
					this.SendPropertyChanging();
					this._ModelNo = value;
					this.SendPropertyChanged("ModelNo");
					this.OnModelNoChanged();
				}
			}
		}
		
		[Column(Storage="_DateTime", DbType="DateTime NOT NULL")]
		public System.DateTime DateTime
		{
			get
			{
				return this._DateTime;
			}
			set
			{
				if ((this._DateTime != value))
				{
					this.OnDateTimeChanging(value);
					this.SendPropertyChanging();
					this._DateTime = value;
					this.SendPropertyChanged("DateTime");
					this.OnDateTimeChanged();
				}
			}
		}
		
		[Column(Storage="_SystemID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SystemID
		{
			get
			{
				return this._SystemID;
			}
			set
			{
				if ((this._SystemID != value))
				{
					this.OnSystemIDChanging(value);
					this.SendPropertyChanging();
					this._SystemID = value;
					this.SendPropertyChanged("SystemID");
					this.OnSystemIDChanged();
				}
			}
		}
		
		[Column(Storage="_OpID", DbType="NVarChar(16) NOT NULL", CanBeNull=false)]
		public string OpID
		{
			get
			{
				return this._OpID;
			}
			set
			{
				if ((this._OpID != value))
				{
					this.OnOpIDChanging(value);
					this.SendPropertyChanging();
					this._OpID = value;
					this.SendPropertyChanged("OpID");
					this.OnOpIDChanged();
				}
			}
		}
		
		[Column(Storage="_TestType", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string TestType
		{
			get
			{
				return this._TestType;
			}
			set
			{
				if ((this._TestType != value))
				{
					this.OnTestTypeChanging(value);
					this.SendPropertyChanging();
					this._TestType = value;
					this.SendPropertyChanged("TestType");
					this.OnTestTypeChanged();
				}
			}
		}
		
		[Column(Storage="_TestResult", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TestResult
		{
			get
			{
				return this._TestResult;
			}
			set
			{
				if ((this._TestResult != value))
				{
					this.OnTestResultChanging(value);
					this.SendPropertyChanging();
					this._TestResult = value;
					this.SendPropertyChanged("TestResult");
					this.OnTestResultChanged();
				}
			}
		}
		
		[Column(Storage="_TestPort", DbType="NVarChar(25)")]
		public string TestPort
		{
			get
			{
				return this._TestPort;
			}
			set
			{
				if ((this._TestPort != value))
				{
					this.OnTestPortChanging(value);
					this.SendPropertyChanging();
					this._TestPort = value;
					this.SendPropertyChanged("TestPort");
					this.OnTestPortChanged();
				}
			}
		}
		
		[Association(Name="UutRecord_UutDefect", Storage="_UutDefects", ThisKey="ID", OtherKey="UutRecordID")]
		public EntitySet<UutDefect> UutDefects
		{
			get
			{
				return this._UutDefects;
			}
			set
			{
				this._UutDefects.Assign(value);
			}
		}
		
		[Association(Name="UutRecord_UutRecordDetail", Storage="_UutRecordDetails", ThisKey="ID", OtherKey="UutRecordID")]
		public EntitySet<UutRecordDetail> UutRecordDetails
		{
			get
			{
				return this._UutRecordDetails;
			}
			set
			{
				this._UutRecordDetails.Assign(value);
			}
		}
		
		[Association(Name="Model_UutRecord", Storage="_Model", ThisKey="ModelNo", OtherKey="ModelNo", IsForeignKey=true)]
		public Model Model
		{
			get
			{
				return this._Model.Entity;
			}
			set
			{
				Model previousValue = this._Model.Entity;
				if (((previousValue != value) 
							|| (this._Model.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Model.Entity = null;
						previousValue.UutRecords.Remove(this);
					}
					this._Model.Entity = value;
					if ((value != null))
					{
						value.UutRecords.Add(this);
						this._ModelNo = value.ModelNo;
					}
					else
					{
						this._ModelNo = default(string);
					}
					this.SendPropertyChanged("Model");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_UutDefects(UutDefect entity)
		{
			this.SendPropertyChanging();
			entity.UutRecord = this;
		}
		
		private void detach_UutDefects(UutDefect entity)
		{
			this.SendPropertyChanging();
			entity.UutRecord = null;
		}
		
		private void attach_UutRecordDetails(UutRecordDetail entity)
		{
			this.SendPropertyChanging();
			entity.UutRecord = this;
		}
		
		private void detach_UutRecordDetails(UutRecordDetail entity)
		{
			this.SendPropertyChanging();
			entity.UutRecord = null;
		}
	}
	
	[Table(Name="dbo.ModelXRef")]
	public partial class ModelXRef : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private string _ModelNo;
		
		private string _ScannedChars;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnModelNoChanging(string value);
    partial void OnModelNoChanged();
    partial void OnScannedCharsChanging(string value);
    partial void OnScannedCharsChanged();
    #endregion
		
		public ModelXRef()
		{
			OnCreated();
		}
		
		[Column(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[Column(Storage="_ModelNo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ModelNo
		{
			get
			{
				return this._ModelNo;
			}
			set
			{
				if ((this._ModelNo != value))
				{
					this.OnModelNoChanging(value);
					this.SendPropertyChanging();
					this._ModelNo = value;
					this.SendPropertyChanged("ModelNo");
					this.OnModelNoChanged();
				}
			}
		}
		
		[Column(Storage="_ScannedChars", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ScannedChars
		{
			get
			{
				return this._ScannedChars;
			}
			set
			{
				if ((this._ScannedChars != value))
				{
					this.OnScannedCharsChanging(value);
					this.SendPropertyChanging();
					this._ScannedChars = value;
					this.SendPropertyChanged("ScannedChars");
					this.OnScannedCharsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
