//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTIWindowsControlLibrary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VtiLibLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VtiLibLocalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VTIWindowsControlLibrary.VtiLibLocalization", typeof(VtiLibLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove operator &apos;{0}&apos;?.
        /// </summary>
        internal static string AskRemoveOperator {
            get {
                return ResourceManager.GetString("AskRemoveOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital I/O Control.
        /// </summary>
        internal static string DigitalIOControl {
            get {
                return ResourceManager.GetString("DigitalIOControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital I/O Control (INACTIVE).
        /// </summary>
        internal static string DigitalIOControlInactive {
            get {
                return ResourceManager.GetString("DigitalIOControlInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital I/O Safety Warning.
        /// </summary>
        internal static string DigitalIOWarning {
            get {
                return ResourceManager.GetString("DigitalIOWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &apos;{0}&apos; does not have permission to execute the command &apos;{1}&apos;..
        /// </summary>
        internal static string DoesNotHavePermission {
            get {
                return ResourceManager.GetString("DoesNotHavePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed Time.
        /// </summary>
        internal static string ElapsedTime {
            get {
                return ResourceManager.GetString("ElapsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured retrieving the process value for the &apos;{0}&apos; parameter of the &apos;{1}&apos; model from the database..
        /// </summary>
        internal static string ErrorGettingProcessValue {
            get {
                return ResourceManager.GetString("ErrorGettingProcessValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured loading model &apos;{0}&apos;..
        /// </summary>
        internal static string ErrorLoadingModel {
            get {
                return ResourceManager.GetString("ErrorLoadingModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured setting the process value for the &apos;{0}&apos; parameter.  The value supplied was &apos;{1}&apos;..
        /// </summary>
        internal static string ErrorSettingProcessValue {
            get {
                return ResourceManager.GetString("ErrorSettingProcessValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        internal static string hours {
            get {
                return ResourceManager.GetString("hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing Configuration....
        /// </summary>
        internal static string InitializingConfig {
            get {
                return ResourceManager.GetString("InitializingConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing Database....
        /// </summary>
        internal static string InitializingDatabase {
            get {
                return ResourceManager.GetString("InitializingDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing I/O Interface....
        /// </summary>
        internal static string InitializingIOInterface {
            get {
                return ResourceManager.GetString("InitializingIOInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing Machine....
        /// </summary>
        internal static string InitializingMachine {
            get {
                return ResourceManager.GetString("InitializingMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing Manual Commands....
        /// </summary>
        internal static string InitializingManualCommands {
            get {
                return ResourceManager.GetString("InitializingManualCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing Resource Manager....
        /// </summary>
        internal static string InitializingResourceManager {
            get {
                return ResourceManager.GetString("InitializingResourceManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Commands.
        /// </summary>
        internal static string ManualCommands {
            get {
                return ResourceManager.GetString("ManualCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string minutes {
            get {
                return ResourceManager.GetString("minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Deleted.
        /// </summary>
        internal static string ModelDeleted {
            get {
                return ResourceManager.GetString("ModelDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; in model &apos;{1}&apos; changed from {2} to {3}.
        /// </summary>
        internal static string ModelParameterChanged {
            get {
                return ResourceManager.GetString("ModelParameterChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Model Added.
        /// </summary>
        internal static string NewModelAdded {
            get {
                return ResourceManager.GetString("NewModelAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords don&apos;t match!  Please re-enter..
        /// </summary>
        internal static string PasswordsDontMatch {
            get {
                return ResourceManager.GetString("PasswordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a password!.
        /// </summary>
        internal static string PleaseEnterPassword {
            get {
                return ResourceManager.GetString("PleaseEnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please log in to the system first..
        /// </summary>
        internal static string PleaseLogIn {
            get {
                return ResourceManager.GetString("PleaseLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schematic Safety Warning.
        /// </summary>
        internal static string SchematicWarning {
            get {
                return ResourceManager.GetString("SchematicWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string seconds {
            get {
                return ResourceManager.GetString("seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Model.
        /// </summary>
        internal static string SelectModel {
            get {
                return ResourceManager.GetString("SelectModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Failed.
        /// </summary>
        internal static string StepFailed {
            get {
                return ResourceManager.GetString("StepFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Schematic.
        /// </summary>
        internal static string SystemSchematic {
            get {
                return ResourceManager.GetString("SystemSchematic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Schematic (INACTIVE).
        /// </summary>
        internal static string SystemSchematicInactive {
            get {
                return ResourceManager.GetString("SystemSchematicInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Remaining.
        /// </summary>
        internal static string TimeRemaining {
            get {
                return ResourceManager.GetString("TimeRemaining", resourceCulture);
            }
        }
    }
}
