//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTIWindowsControlLibrary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VtiStandardMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VtiStandardMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VTIWindowsControlLibrary.VtiStandardMessages", typeof(VtiStandardMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connector Check.
        /// </summary>
        internal static string ConnectorCheck {
            get {
                return ResourceManager.GetString("ConnectorCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO TEST: Connector check failed!.
        /// </summary>
        internal static string ConnectorCheck_Failed {
            get {
                return ResourceManager.GetString("ConnectorCheck_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO TEST: Connector.
        /// </summary>
        internal static string ConnectorCheck_FailedTH {
            get {
                return ResourceManager.GetString("ConnectorCheck_FailedTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connector check passed..
        /// </summary>
        internal static string ConnectorCheck_Passed {
            get {
                return ResourceManager.GetString("ConnectorCheck_Passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing connector check....
        /// </summary>
        internal static string ConnectorCheck_Prompt {
            get {
                return ResourceManager.GetString("ConnectorCheck_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incremental Evacuation.
        /// </summary>
        internal static string IncEvac {
            get {
                return ResourceManager.GetString("IncEvac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAILED: Incremental evacuation check.
        /// </summary>
        internal static string IncEvac_Failed {
            get {
                return ResourceManager.GetString("IncEvac_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAILED: Inc Evac.
        /// </summary>
        internal static string IncEvac_FailedTH {
            get {
                return ResourceManager.GetString("IncEvac_FailedTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit passed the incremental evacuation check..
        /// </summary>
        internal static string IncEvac_Passed {
            get {
                return ResourceManager.GetString("IncEvac_Passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAILED: Unit failed the incremental evacuation check.  Gross leak detected.  Press ACKNOWLEDGE to continue....
        /// </summary>
        internal static string IncEvac_PromptFailed {
            get {
                return ResourceManager.GetString("IncEvac_PromptFailed", resourceCulture);
            }
        }
    }
}
